export const ActionTypes = {
  ERROR: 'ERROR',
  RESET_ERROR: 'RESET_ERROR',
  GET_USER: 'GET_USER',
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_EVENT: 'GET_EVENT',
  GET_EVENTS: 'GET_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT'
}
